# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.vx_lan_stack import VxLANStack

class TestVxLANStack(unittest.TestCase):
    """VxLANStack unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VxLANStack:
        """Test VxLANStack
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VxLANStack`
        """
        model = VxLANStack()
        if include_optional:
            return VxLANStack(
                inner_ip_range = cyperf.models.ip_range.IPRange(
                    automatic_ip_type = null, 
                    count = 56, 
                    gw_auto = True, 
                    gw_start = '::02:84:9:0cc0:F:CCf', 
                    host_count = 56, 
                    inner_vlan_range = null, 
                    ip_auto = True, 
                    ip_incr = '::02:84:9:0cc0:F:CCf', 
                    ip_range_name = 'YBuLd', 
                    ip_start = '::02:84:9:0cc0:F:CCf', 
                    ip_ver = null, 
                    is_emulated_router = True, 
                    mss = 56, 
                    mss_auto = True, 
                    net_mask = 56, 
                    net_mask_auto = True, 
                    id = '', 
                    links = [
                        cyperf.models.api_link.APILink(
                            content_type = '', 
                            href = '', 
                            method = '', 
                            name = '', 
                            references_count = 56, 
                            rel = '', 
                            type = '', )
                        ], 
                    max_count_per_agent = 56, 
                    network_tags = [
                        ''
                        ], ),
                outer_ip_range = cyperf.models.ip_range.IPRange(
                    automatic_ip_type = null, 
                    count = 56, 
                    gw_auto = True, 
                    gw_start = '::02:84:9:0cc0:F:CCf', 
                    host_count = 56, 
                    inner_vlan_range = null, 
                    ip_auto = True, 
                    ip_incr = '::02:84:9:0cc0:F:CCf', 
                    ip_range_name = 'YBuLd', 
                    ip_start = '::02:84:9:0cc0:F:CCf', 
                    ip_ver = null, 
                    is_emulated_router = True, 
                    mss = 56, 
                    mss_auto = True, 
                    net_mask = 56, 
                    net_mask_auto = True, 
                    id = '', 
                    links = [
                        cyperf.models.api_link.APILink(
                            content_type = '', 
                            href = '', 
                            method = '', 
                            name = '', 
                            references_count = 56, 
                            rel = '', 
                            type = '', )
                        ], 
                    max_count_per_agent = 56, 
                    network_tags = [
                        ''
                        ], ),
                vx_lan_range = cyperf.models.vx_lan_range.VxLANRange(
                    hacked_inner_remote_ip_incr = '::02:84:9:0cc0:F:CCf', 
                    hacked_inner_remote_ip_start = '::02:84:9:0cc0:F:CCf', 
                    md2_tlvs = [
                        cyperf.models.md2_tlv.Md2Tlv(
                            md2_class = 56, 
                            md2_type = 56, 
                            md2_value = 56, 
                            id = '', )
                        ], 
                    remote_vtep_ip_local_count = 56, 
                    remote_vtep_ip_local_incr = '::02:84:9:0cc0:F:CCf', 
                    remote_vtep_ip_range_incr = '::02:84:9:0cc0:F:CCf', 
                    remote_vtep_ip_start = '::02:84:9:0cc0:F:CCf', 
                    total_tunnel_count = 56, 
                    use_vx_lan_ids = True, 
                    vx_lanid_incr = 56, 
                    vx_lanid_per_vtep_pair_count = 56, 
                    vx_lanid_start = 56, 
                    vx_lan_ids = [
                        cyperf.models.vx_lanid.VxLANId(
                            vx_lan_id = 56, 
                            id = '', )
                        ], 
                    vx_lan_range_name = 'YBuLd', 
                    id = '', 
                    links = [
                        cyperf.models.api_link.APILink(
                            content_type = '', 
                            href = '', 
                            method = '', 
                            name = '', 
                            references_count = 56, 
                            rel = '', 
                            type = '', )
                        ], ),
                vx_lan_stack_name = 'YBuLd',
                id = '',
                links = [
                    cyperf.models.api_link.APILink(
                        content_type = '', 
                        href = '', 
                        method = '', 
                        name = '', 
                        references_count = 56, 
                        rel = '', 
                        type = '', )
                    ]
            )
        else:
            return VxLANStack(
                vx_lan_stack_name = 'YBuLd',
                id = '',
        )
        """

    def testVxLANStack(self):
        """Test VxLANStack"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
