# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.md2_tlv import Md2Tlv

class TestMd2Tlv(unittest.TestCase):
    """Md2Tlv unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Md2Tlv:
        """Test Md2Tlv
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Md2Tlv`
        """
        model = Md2Tlv()
        if include_optional:
            return Md2Tlv(
                md2_class = 56,
                md2_type = 56,
                md2_value = 56,
                id = ''
            )
        else:
            return Md2Tlv(
                md2_class = 56,
                md2_type = 56,
                md2_value = 56,
                id = '',
        )
        """

    def testMd2Tlv(self):
        """Test Md2Tlv"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
