# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.vx_lanid import VxLANId

class TestVxLANId(unittest.TestCase):
    """VxLANId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VxLANId:
        """Test VxLANId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VxLANId`
        """
        model = VxLANId()
        if include_optional:
            return VxLANId(
                vx_lan_id = 56,
                id = ''
            )
        else:
            return VxLANId(
                vx_lan_id = 56,
                id = '',
        )
        """

    def testVxLANId(self):
        """Test VxLANId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
