# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.appsec_app import AppsecApp

class TestAppsecApp(unittest.TestCase):
    """AppsecApp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppsecApp:
        """Test AppsecApp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppsecApp`
        """
        model = AppsecApp()
        if include_optional:
            return AppsecApp(
                app = None,
                description = '',
                id = '',
                last_modified = 56,
                links = [
                    cyperf.models.api_link.APILink(
                        content_type = '', 
                        href = '', 
                        method = '', 
                        name = '', 
                        references_count = 56, 
                        rel = '', 
                        type = '', )
                    ],
                name = '',
                owner = '',
                owner_id = '',
                static = True,
                user_defined = True
            )
        else:
            return AppsecApp(
        )
        """

    def testAppsecApp(self):
        """Test AppsecApp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
