# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.quic_profile import QUICProfile

class TestQUICProfile(unittest.TestCase):
    """QUICProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QUICProfile:
        """Test QUICProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QUICProfile`
        """
        model = QUICProfile()
        if include_optional:
            return QUICProfile(
                client_tls_profile = cyperf.models.tls_profile.TLSProfile(
                    certificate_file = null, 
                    cipher = null, 
                    cipher12 = null, 
                    cipher13 = null, 
                    ciphers12 = [
                        'ECDHE-RSA-AES256-GCM-SHA384'
                        ], 
                    ciphers13 = [
                        'AES-256-GCM-SHA384'
                        ], 
                    dh_file = null, 
                    get_tls_conflicts = [
                        'YQ=='
                        ], 
                    groups13 = [
                        cyperf.models.group_tls13.GroupTLS13(
                            is_deprecated = True, 
                            name = 'P-256', )
                        ], 
                    immediate_close = True, 
                    key_file = null, 
                    key_file_password = '', 
                    links = [
                        cyperf.models.api_link.APILink(
                            content_type = '', 
                            href = '', 
                            method = '', 
                            name = '', 
                            references_count = 56, 
                            rel = '', 
                            type = '', )
                        ], 
                    middle_box_enabled = True, 
                    profile_id = '', 
                    resolve_tls_conflicts = [
                        cyperf.models.conflict.Conflict(
                            name = '', 
                            path_to_target = '', 
                            path_vars = {
                                'key' : ''
                                }, )
                        ], 
                    send_close_notify = True, 
                    session_reuse_count = 56, 
                    session_reuse_method = null, 
                    session_reuse_method12 = null, 
                    session_reuse_method13 = null, 
                    sni_cert_configs = [
                        cyperf.models.cert_config.CertConfig(
                            certificate_file = null, 
                            dh_file = null, 
                            get_sni_conflicts = [
                                'YQ=='
                                ], 
                            id = '', 
                            is_playlist = True, 
                            key_file = null, 
                            key_file_password = '', 
                            playlist_column_name = '', 
                            playlist_filename = '', 
                            resolve_sni_conflicts = [
                                cyperf.models.conflict.Conflict(
                                    name = '', 
                                    path_to_target = '', 
                                    path_vars = {
                                        'key' : ''
                                        }, )
                                ], 
                            sni_hostname = '', )
                        ], 
                    sni_enabled = True, 
                    supported_groups13 = [
                        'P-256'
                        ], 
                    tls12_enabled = True, 
                    tls13_enabled = True, 
                    use_tls_profile = True, 
                    version = 'NONE', ),
                min_rto = 56,
                name = '',
                quic_version = 'Q043',
                rx_buffer = 56,
                server_tls_profile = cyperf.models.tls_profile.TLSProfile(
                    certificate_file = null, 
                    cipher = null, 
                    cipher12 = null, 
                    cipher13 = null, 
                    ciphers12 = [
                        'ECDHE-RSA-AES256-GCM-SHA384'
                        ], 
                    ciphers13 = [
                        'AES-256-GCM-SHA384'
                        ], 
                    dh_file = null, 
                    get_tls_conflicts = [
                        'YQ=='
                        ], 
                    groups13 = [
                        cyperf.models.group_tls13.GroupTLS13(
                            is_deprecated = True, 
                            name = 'P-256', )
                        ], 
                    immediate_close = True, 
                    key_file = null, 
                    key_file_password = '', 
                    links = [
                        cyperf.models.api_link.APILink(
                            content_type = '', 
                            href = '', 
                            method = '', 
                            name = '', 
                            references_count = 56, 
                            rel = '', 
                            type = '', )
                        ], 
                    middle_box_enabled = True, 
                    profile_id = '', 
                    resolve_tls_conflicts = [
                        cyperf.models.conflict.Conflict(
                            name = '', 
                            path_to_target = '', 
                            path_vars = {
                                'key' : ''
                                }, )
                        ], 
                    send_close_notify = True, 
                    session_reuse_count = 56, 
                    session_reuse_method = null, 
                    session_reuse_method12 = null, 
                    session_reuse_method13 = null, 
                    sni_cert_configs = [
                        cyperf.models.cert_config.CertConfig(
                            certificate_file = null, 
                            dh_file = null, 
                            get_sni_conflicts = [
                                'YQ=='
                                ], 
                            id = '', 
                            is_playlist = True, 
                            key_file = null, 
                            key_file_password = '', 
                            playlist_column_name = '', 
                            playlist_filename = '', 
                            resolve_sni_conflicts = [
                                cyperf.models.conflict.Conflict(
                                    name = '', 
                                    path_to_target = '', 
                                    path_vars = {
                                        'key' : ''
                                        }, )
                                ], 
                            sni_hostname = '', )
                        ], 
                    sni_enabled = True, 
                    supported_groups13 = [
                        'P-256'
                        ], 
                    tls12_enabled = True, 
                    tls13_enabled = True, 
                    use_tls_profile = True, 
                    version = 'NONE', ),
                links = [
                    cyperf.models.api_link.APILink(
                        content_type = '', 
                        href = '', 
                        method = '', 
                        name = '', 
                        references_count = 56, 
                        rel = '', 
                        type = '', )
                    ]
            )
        else:
            return QUICProfile(
        )
        """

    def testQUICProfile(self):
        """Test QUICProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
