# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.get_apps_operation import GetAppsOperation

class TestGetAppsOperation(unittest.TestCase):
    """GetAppsOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAppsOperation:
        """Test GetAppsOperation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAppsOperation`
        """
        model = GetAppsOperation()
        if include_optional:
            return GetAppsOperation(
                categories = [
                    cyperf.models.category_filter.CategoryFilter(
                        category = '', 
                        values = [
                            ''
                            ], )
                    ],
                filter_mode = '',
                search_col = [
                    ''
                    ],
                search_val = [
                    ''
                    ],
                skip = '',
                sort = [
                    cyperf.models.sort_body_field.SortBodyField(
                        field = '', 
                        order = '', )
                    ],
                take = ''
            )
        else:
            return GetAppsOperation(
        )
        """

    def testGetAppsOperation(self):
        """Test GetAppsOperation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
