# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.get_config_categorie_subcategories200_response_one_of import GetConfigCategorieSubcategories200ResponseOneOf

class TestGetConfigCategorieSubcategories200ResponseOneOf(unittest.TestCase):
    """GetConfigCategorieSubcategories200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetConfigCategorieSubcategories200ResponseOneOf:
        """Test GetConfigCategorieSubcategories200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetConfigCategorieSubcategories200ResponseOneOf`
        """
        model = GetConfigCategorieSubcategories200ResponseOneOf()
        if include_optional:
            return GetConfigCategorieSubcategories200ResponseOneOf(
                data = [
                    cyperf.models.config_sub_category.ConfigSubCategory(
                        display_name = '', )
                    ],
                total_count = 56
            )
        else:
            return GetConfigCategorieSubcategories200ResponseOneOf(
        )
        """

    def testGetConfigCategorieSubcategories200ResponseOneOf(self):
        """Test GetConfigCategorieSubcategories200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
