# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.appsec_app_metadata_keywords_inner import AppsecAppMetadataKeywordsInner

class TestAppsecAppMetadataKeywordsInner(unittest.TestCase):
    """AppsecAppMetadataKeywordsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppsecAppMetadataKeywordsInner:
        """Test AppsecAppMetadataKeywordsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppsecAppMetadataKeywordsInner`
        """
        model = AppsecAppMetadataKeywordsInner()
        if include_optional:
            return AppsecAppMetadataKeywordsInner(
            )
        else:
            return AppsecAppMetadataKeywordsInner(
        )
        """

    def testAppsecAppMetadataKeywordsInner(self):
        """Test AppsecAppMetadataKeywordsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
