# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.config_sub_category import ConfigSubCategory

class TestConfigSubCategory(unittest.TestCase):
    """ConfigSubCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigSubCategory:
        """Test ConfigSubCategory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigSubCategory`
        """
        model = ConfigSubCategory()
        if include_optional:
            return ConfigSubCategory(
                display_name = ''
            )
        else:
            return ConfigSubCategory(
        )
        """

    def testConfigSubCategory(self):
        """Test ConfigSubCategory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
