# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.group_tls13 import GroupTLS13

class TestGroupTLS13(unittest.TestCase):
    """GroupTLS13 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupTLS13:
        """Test GroupTLS13
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupTLS13`
        """
        model = GroupTLS13()
        if include_optional:
            return GroupTLS13(
                is_deprecated = True,
                name = 'P-256'
            )
        else:
            return GroupTLS13(
                is_deprecated = True,
                name = 'P-256',
        )
        """

    def testGroupTLS13(self):
        """Test GroupTLS13"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
