# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.update_port_tags_operation import UpdatePortTagsOperation

class TestUpdatePortTagsOperation(unittest.TestCase):
    """UpdatePortTagsOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePortTagsOperation:
        """Test UpdatePortTagsOperation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePortTagsOperation`
        """
        model = UpdatePortTagsOperation()
        if include_optional:
            return UpdatePortTagsOperation(
                controllers = [
                    cyperf.models.ports_by_controller.PortsByController(
                        compute_nodes = [
                            cyperf.models.ports_by_node.PortsByNode(
                                compute_node_id = '', 
                                ports = [
                                    ''
                                    ], )
                            ], 
                        controller_id = '', )
                    ],
                tags_to_add = [
                    ''
                    ],
                tags_to_remove = [
                    ''
                    ]
            )
        else:
            return UpdatePortTagsOperation(
        )
        """

    def testUpdatePortTagsOperation(self):
        """Test UpdatePortTagsOperation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
