# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class ChassisInfo(BaseModel):
    """
    ChassisInfo
    """ # noqa: E501
    aggregated_mode: Optional[StrictBool] = Field(default=None, description="Whether the ports of this compute node are aggregated", alias="aggregatedMode")
    checkout_id: Optional[StrictInt] = Field(default=None, description="The id of the compute node used for checkout licenses", alias="checkoutID")
    compute_node_id: Optional[StrictStr] = Field(default=None, description="The id of the compute node where the agent is running", alias="computeNodeID")
    front_panel_port_id: Optional[StrictStr] = Field(default=None, description="The ID of the Front Panel Port", alias="frontPanelPortID")
    hw_platform: Optional[StrictStr] = Field(default=None, description="The hardware platform the corresponding port is running on", alias="hwPlatform")
    hw_revision: Optional[StrictStr] = Field(default=None, description="The hardware revision of the underlying platform", alias="hwRevision")
    port_id: Optional[StrictStr] = Field(default=None, description="The id of the corresponding port", alias="portID")
    __properties: ClassVar[List[str]] = ["aggregatedMode", "checkoutID", "computeNodeID", "frontPanelPortID", "hwPlatform", "hwRevision", "portID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChassisInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "aggregated_mode",
            "checkout_id",
            "compute_node_id",
            "front_panel_port_id",
            "hw_platform",
            "hw_revision",
            "port_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChassisInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "aggregatedMode": obj.get("aggregatedMode"),
                        "checkoutID": obj.get("checkoutID"),
                        "computeNodeID": obj.get("computeNodeID"),
                        "frontPanelPortID": obj.get("frontPanelPortID"),
                        "hwPlatform": obj.get("hwPlatform"),
                        "hwRevision": obj.get("hwRevision"),
                        "portID": obj.get("portID")
            ,
            "links": obj.get("links")
        })
        return _obj


