# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ClassicalSignatureAlgorithmTLS13(str, Enum):
    """
    The TLS supported classical signature algorithms.
    """

    """
    allowed enum values
    """
    RSA_PKCS1_SHA256 = 'rsa_pkcs1_sha256'
    RSA_PKCS1_SHA384 = 'rsa_pkcs1_sha384'
    RSA_PKCS1_SHA512 = 'rsa_pkcs1_sha512'
    ECDSA_SECP256R1_SHA256 = 'ecdsa_secp256r1_sha256'
    ECDSA_SECP384R1_SHA384 = 'ecdsa_secp384r1_sha384'
    ECDSA_SECP521R1_SHA512 = 'ecdsa_secp521r1_sha512'
    RSA_PSS_RSAE_SHA256 = 'rsa_pss_rsae_sha256'
    RSA_PSS_RSAE_SHA384 = 'rsa_pss_rsae_sha384'
    RSA_PSS_RSAE_SHA512 = 'rsa_pss_rsae_sha512'
    RSA_PSS_PSS_SHA256 = 'rsa_pss_pss_sha256'
    RSA_PSS_PSS_SHA384 = 'rsa_pss_pss_sha384'
    RSA_PSS_PSS_SHA512 = 'rsa_pss_pss_sha512'
    ED25519 = 'ed25519'
    ED448 = 'ed448'
    ECDSA_BRAINPOOLP256R1TLS13_SHA256 = 'ecdsa_brainpoolp256r1tls13_sha256'
    ECDSA_BRAINPOOLP384R1TLS13_SHA384 = 'ecdsa_brainpoolp384r1tls13_sha384'
    ECDSA_BRAINPOOLP512R1TLS13_SHA512 = 'ecdsa_brainpoolp512r1tls13_sha512'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ClassicalSignatureAlgorithmTLS13 from a JSON string"""
        return cls(json.loads(json_str))


