# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CompositePqcSignatureAlgorithmTLS13(str, Enum):
    """
    The TLSv1.3 supported composite PQC signature algorithms.
    """

    """
    allowed enum values
    """
    P256_MLDSA44 = 'p256_mldsa44'
    P384_MLDSA65 = 'p384_mldsa65'
    P521_MLDSA87 = 'p521_mldsa87'
    RSA3072_MLDSA44 = 'rsa3072_mldsa44'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CompositePqcSignatureAlgorithmTLS13 from a JSON string"""
        return cls(json.loads(json_str))


