# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyperf.models.text_segment import TextSegment
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class ContentBlock(BaseModel):
    """
    ContentBlock
    """ # noqa: E501
    content: Optional[List[TextSegment]] = Field(default=None, description="The content of the block, as a list of rich text segments.")
    level: Optional[StrictInt] = Field(default=None, description="The heading level (1-6), used by heading blocks.")
    list_style: Optional[StrictStr] = Field(default=None, description="The list style: ordered or unordered (used by list blocks).", alias="listStyle")
    severity: Optional[StrictStr] = Field(default=None, description="The severity level of a note block: info, warning, error, or success.")
    type: Optional[StrictStr] = Field(default=None, description="The type of content block (e.g. paragraph, list, note, heading, divider).")
    __properties: ClassVar[List[str]] = ["content", "level", "listStyle", "severity", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContentBlock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in content (list)
        _items = []
        if self.content:
            for _item in self.content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['content'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContentBlock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "content": ( [TextSegment.from_dict(_item) for _item in obj.get("content", [])] if obj.get("content") is not None else None),
                        "level": obj.get("level"),
                        "listStyle": obj.get("listStyle"),
                        "severity": obj.get("severity"),
                        "type": obj.get("type")
            ,
            "links": obj.get("links")
        })
        return _obj


