# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyperf.models.advanced_metric import AdvancedMetric
from cyperf.models.appsec_app_metadata_keywords_inner import AppsecAppMetadataKeywordsInner
from cyperf.models.data_source_details import DataSourceDetails
from cyperf.models.grid_position import GridPosition
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class Panel(BaseModel):
    """
    Panel
    """ # noqa: E501
    filters: Optional[List[Dict[str, AppsecAppMetadataKeywordsInner]]] = Field(default=None, description="The filters to be applied to the panel stats")
    group_by: Optional[List[AdvancedMetric]] = Field(default=None, description="The stats to be used as group by clauses", alias="groupBy")
    limit: Optional[StrictInt] = Field(default=None, description="The maximum number of stats to be generated in a certain interval")
    metrics: Optional[List[AdvancedMetric]] = Field(default=None, description="The stats to be displayed in the panel")
    panel_data_source: Optional[DataSourceDetails] = Field(default=None, alias="panelDataSource")
    panel_type: Optional[StrictStr] = Field(default=None, description="The type of the panel", alias="panelType")
    position: Optional[GridPosition] = None
    stats_sources: Optional[List[StrictStr]] = Field(default=None, description="The sources of the statistics based on the panel configuration", alias="statsSources")
    title: Optional[StrictStr] = Field(default=None, description="The title of the panel")
    __properties: ClassVar[List[str]] = ["filters", "groupBy", "limit", "metrics", "panelDataSource", "panelType", "position", "statsSources", "title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Panel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item in self.filters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in group_by (list)
        _items = []
        if self.group_by:
            for _item in self.group_by:
                if _item:
                    _items.append(_item.to_dict())
            _dict['groupBy'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metrics (list)
        _items = []
        if self.metrics:
            for _item in self.metrics:
                if _item:
                    _items.append(_item.to_dict())
            _dict['metrics'] = _items
        # override the default output from pydantic by calling `to_dict()` of panel_data_source
        if self.panel_data_source:
            _dict['panelDataSource'] = self.panel_data_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Panel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "filters": ( [Dict.from_dict(_item) for _item in obj.get("filters", [])] if obj.get("filters") is not None else None),
                        "groupBy": ( [AdvancedMetric.from_dict(_item) for _item in obj.get("groupBy", [])] if obj.get("groupBy") is not None else None),
                        "limit": obj.get("limit"),
                        "metrics": ( [AdvancedMetric.from_dict(_item) for _item in obj.get("metrics", [])] if obj.get("metrics") is not None else None),
                        "panelDataSource": DataSourceDetails.from_dict(obj["panelDataSource"]) if obj.get("panelDataSource") is not None else None,
                        "panelType": obj.get("panelType"),
                        "position": GridPosition.from_dict(obj["position"]) if obj.get("position") is not None else None,
                        "statsSources": obj.get("statsSources") if obj.get("statsSources") is not None else [],
                        "title": obj.get("title")
            ,
            "links": obj.get("links")
        })
        return _obj


