# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PqcKemGroup(str, Enum):
    """
    PqcKemGroup
    """

    """
    allowed enum values
    """
    NONE = 'NONE'
    MODP_768 = 'MODP 768'
    MODP_1024 = 'MODP 1024'
    MODP_1536 = 'MODP 1536'
    MODP_2048 = 'MODP 2048'
    MODP_3072 = 'MODP 3072'
    MODP_4096 = 'MODP 4096'
    MODP_6144 = 'MODP 6144'
    MODP_8192 = 'MODP 8192'
    MODP_1024_S160 = 'MODP 1024 S160'
    MODP_2048_S224 = 'MODP 2048 S224'
    MODP_2048_S256 = 'MODP 2048 S256'
    ECP_192 = 'ECP 192'
    ECP_224 = 'ECP 224'
    ECP_256 = 'ECP 256'
    ECP_384 = 'ECP 384'
    ECP_521 = 'ECP 521'
    ECP_224_BP = 'ECP 224 BP'
    ECP_256_BP = 'ECP 256 BP'
    ECP_384_BP = 'ECP 384 BP'
    ECP_512_BP = 'ECP 512 BP'
    MLKEM512 = 'MLKEM512'
    MLKEM768 = 'MLKEM768'
    MLKEM1024 = 'MLKEM1024'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PqcKemGroup from a JSON string"""
        return cls(json.loads(json_str))


