# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PqcSignatureAlgorithmTLS13(str, Enum):
    """
    The TLSv1.3 supported PQC signature algorithms.
    """

    """
    allowed enum values
    """
    MLDSA44 = 'mldsa44'
    MLDSA65 = 'mldsa65'
    MLDSA87 = 'mldsa87'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PqcSignatureAlgorithmTLS13 from a JSON string"""
        return cls(json.loads(json_str))


