# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class Profile(BaseModel):
    """
    Profile
    """ # noqa: E501
    category: Optional[StrictStr] = Field(default=None, description="Category of the profile")
    config_id: Optional[StrictStr] = Field(default=None, description="The config ID associated with this profile", alias="configId")
    description: Optional[StrictStr] = Field(default=None, description="Description of the profile")
    display_name: Optional[StrictStr] = Field(default=None, description="Display name of the profile", alias="displayName")
    icon: Optional[StrictStr] = Field(default=None, description="Profile icon (base64 encoded)")
    id: Optional[StrictStr] = None
    index: Optional[StrictInt] = Field(default=None, description="The index of the profile in the list of profiles. This is used for ordering profiles.")
    owner: Optional[StrictStr] = Field(default=None, description="The friendly display name of the profile's owner")
    owner_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the profile's owner", alias="ownerId")
    topology_img_dark: Optional[StrictStr] = Field(default=None, description="Topology image (dark theme, base64 encoded)", alias="topologyImgDark")
    topology_img_light: Optional[StrictStr] = Field(default=None, description="Topology image (light theme, base64 encoded)", alias="topologyImgLight")
    __properties: ClassVar[List[str]] = ["category", "configId", "description", "displayName", "icon", "id", "index", "owner", "ownerId", "topologyImgDark", "topologyImgLight"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Profile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "index",
            "owner",
            "owner_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Profile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "category": obj.get("category"),
                        "configId": obj.get("configId"),
                        "description": obj.get("description"),
                        "displayName": obj.get("displayName"),
                        "icon": obj.get("icon"),
                        "id": obj.get("id"),
                        "index": obj.get("index"),
                        "owner": obj.get("owner"),
                        "ownerId": obj.get("ownerId"),
                        "topologyImgDark": obj.get("topologyImgDark"),
                        "topologyImgLight": obj.get("topologyImgLight")
            ,
            "links": obj.get("links")
        })
        return _obj


