# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyperf.models.api_link import APILink
from cyperf.models.custom_sequence import CustomSequence
from cyperf.models.sequence_data_types import SequenceDataTypes
from cyperf.models.sequence_value_types import SequenceValueTypes
from cyperf.models.simple_sequence_value import SimpleSequenceValue
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class SequenceValue(BaseModel):
    """
    SequenceValue
    """ # noqa: E501
    custom: Optional[CustomSequence] = Field(default=None, alias="Custom")
    data_type: Optional[SequenceDataTypes] = Field(default=None, alias="DataType")
    increment: Optional[SimpleSequenceValue] = Field(default=None, alias="Increment")
    preview: Optional[List[StrictStr]] = Field(default=None, alias="Preview")
    sequence_type: Optional[SequenceValueTypes] = Field(default=None, alias="SequenceType")
    id: Optional[StrictStr] = None
    links: Optional[List[APILink]] = None
    __properties: ClassVar[List[str]] = ["Custom", "DataType", "Increment", "Preview", "SequenceType", "id", "links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SequenceValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom
        if self.custom:
            _dict['Custom'] = self.custom.to_dict()
        # override the default output from pydantic by calling `to_dict()` of increment
        if self.increment:
            _dict['Increment'] = self.increment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SequenceValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "Custom": CustomSequence.from_dict(obj["Custom"]) if obj.get("Custom") is not None else None,
                        "DataType": obj.get("DataType"),
                        "Increment": SimpleSequenceValue.from_dict(obj["Increment"]) if obj.get("Increment") is not None else None,
                        "Preview": obj.get("Preview") if obj.get("Preview") is not None else [],
                        "SequenceType": obj.get("SequenceType"),
                        "id": obj.get("id"),
                        "links": ( [APILink.from_dict(_item) for _item in obj.get("links", [])] if obj.get("links") is not None else None)
            ,
            "links": obj.get("links")
        })
        return _obj


