# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cyperf.models.api_link import APILink
from cyperf.models.params import Params
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class SnowflakeExporter(BaseModel):
    """
    SnowflakeExporter
    """ # noqa: E501
    active: StrictBool = Field(description="Indicates whether the snowflake stats exporter is enabled or not.", alias="Active")
    polling_interval: Optional[Annotated[int, Field(strict=True)]] = Field(default=None, description="Polling interval used for fetching and uploading data.", alias="PollingInterval")
    profile: Optional[Params] = Field(default=None, description="The json snowflake profile.", alias="Profile")
    server_url: StrictStr = Field(description="Snowflake endpoint used for uploading data.", alias="ServerURL")
    links: Optional[List[APILink]] = None
    __properties: ClassVar[List[str]] = ["Active", "PollingInterval", "Profile", "ServerURL", "links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnowflakeExporter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of profile
        if self.profile:
            _dict['Profile'] = self.profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnowflakeExporter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "Active": obj.get("Active"),
                        "PollingInterval": obj.get("PollingInterval"),
                        "Profile": Params.from_dict(obj["Profile"]) if obj.get("Profile") is not None else None,
                        "ServerURL": obj.get("ServerURL"),
                        "links": ( [APILink.from_dict(_item) for _item in obj.get("links", [])] if obj.get("links") is not None else None)
            ,
            "links": obj.get("links")
        })
        return _obj


