# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyperf.models.api_link import APILink
from cyperf.models.change_event import ChangeEvent
from cyperf.models.metrics_list import MetricsList
from cyperf.models.panel import Panel
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class StatsDashboard(BaseModel):
    """
    StatsDashboard
    """ # noqa: E501
    changes: Optional[List[ChangeEvent]] = Field(default=None, description="The changes hook")
    group_id: Optional[StrictStr] = Field(default=None, description="The group identifier of the dashboard", alias="groupId")
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the dashboard")
    links: Optional[List[APILink]] = None
    metrics: Optional[MetricsList] = None
    name: Optional[StrictStr] = Field(default=None, description="The name of the dashboard")
    owner: Optional[StrictStr] = Field(default=None, description="The friendly display name of the entity that created the dashboard")
    owner_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the entity that created the dashboard", alias="ownerId")
    panels: Optional[List[Panel]] = Field(default=None, description="The list of panels in the dashboard")
    read_only: Optional[StrictBool] = Field(default=None, description="Is a read only dashboard", alias="readOnly")
    type: Optional[StrictStr] = Field(default=None, description="The application type of the dashboard")
    __properties: ClassVar[List[str]] = ["changes", "groupId", "id", "links", "metrics", "name", "owner", "ownerId", "panels", "readOnly", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsDashboard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "owner",
            "owner_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in changes (list)
        _items = []
        if self.changes:
            for _item in self.changes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['changes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in panels (list)
        _items = []
        if self.panels:
            for _item in self.panels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['panels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsDashboard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "changes": ( [ChangeEvent.from_dict(_item) for _item in obj.get("changes", [])] if obj.get("changes") is not None else None),
                        "groupId": obj.get("groupId"),
                        "id": obj.get("id"),
                        "links": ( [APILink.from_dict(_item) for _item in obj.get("links", [])] if obj.get("links") is not None else None),
                        "metrics": MetricsList.from_dict(obj["metrics"]) if obj.get("metrics") is not None else None,
                        "name": obj.get("name"),
                        "owner": obj.get("owner"),
                        "ownerId": obj.get("ownerId"),
                        "panels": ( [Panel.from_dict(_item) for _item in obj.get("panels", [])] if obj.get("panels") is not None else None),
                        "readOnly": obj.get("readOnly"),
                        "type": obj.get("type")
            ,
            "links": obj.get("links")
        })
        return _obj


