# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SupportedGroupTLS13(str, Enum):
    """
    The TLSv1.3 supported groups (default: P-256).
    """

    """
    allowed enum values
    """
    P_MINUS_256 = 'P-256'
    P_MINUS_384 = 'P-384'
    P_MINUS_521 = 'P-521'
    X25519_MLKEM512 = 'X25519_MLKEM512'
    X25519_MLKEM768 = 'X25519_MLKEM768'
    MLKEM768 = 'MLKEM768'
    MLKEM512 = 'MLKEM512'
    MLKEM1024 = 'MLKEM1024'
    SECP384R1MLKEM1024 = 'SecP384r1MLKEM1024'
    X448_MLKEM768 = 'X448_MLKEM768'
    P384_MLKEM768 = 'P384_MLKEM768'
    SECP256R1MLKEM768 = 'SecP256r1MLKEM768'
    P256_MLKEM512 = 'P256_MLKEM512'
    X25519 = 'X25519'
    P521_MLKEM1024 = 'P521_MLKEM1024'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupportedGroupTLS13 from a JSON string"""
        return cls(json.loads(json_str))


