# coding: utf-8

"""
    Keysight CyPerf Application API

    Keysight CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VLANType(str, Enum):
    """
    VLANType
    """

    """
    allowed enum values
    """
    VLAN_NONE = 'VLAN_NONE'
    VLAN = 'VLAN'
    VLAN_IN_VLAN = 'VLAN_IN_VLAN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VLANType from a JSON string"""
        return cls(json.loads(json_str))


