# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cyperf.models.api_link import APILink
from cyperf.models.ip_range import IPRange
from cyperf.models.vx_lan_range import VxLANRange
from typing import Optional, Set, Union
from typing_extensions import Self
from pydantic import Field, PrivateAttr

class VxLANStack(BaseModel):
    """
    The VxLAN stack assigned to the current test configuration
    """ # noqa: E501
    inner_ip_range: Optional[IPRange] = Field(default=None, alias="InnerIPRange")
    outer_ip_range: Optional[IPRange] = Field(default=None, alias="OuterIPRange")
    vx_lan_range: Optional[VxLANRange] = Field(default=None, alias="VxLANRange")
    vx_lan_stack_name: Annotated[str, Field(strict=True)] = Field(alias="VxLANStackName")
    id: StrictStr
    links: Optional[List[APILink]] = None
    __properties: ClassVar[List[str]] = ["InnerIPRange", "OuterIPRange", "VxLANRange", "VxLANStackName", "id", "links"]

    @field_validator('vx_lan_stack_name')
    def vx_lan_stack_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^$|^[^\"\\]+$", value):
            raise ValueError(r"must validate the regular expression /^$|^[^\"\\]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VxLANStack from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of inner_ip_range
        if self.inner_ip_range:
            _dict['InnerIPRange'] = self.inner_ip_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of outer_ip_range
        if self.outer_ip_range:
            _dict['OuterIPRange'] = self.outer_ip_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vx_lan_range
        if self.vx_lan_range:
            _dict['VxLANRange'] = self.vx_lan_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VxLANStack from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "InnerIPRange": IPRange.from_dict(obj["InnerIPRange"]) if obj.get("InnerIPRange") is not None else None,
                        "OuterIPRange": IPRange.from_dict(obj["OuterIPRange"]) if obj.get("OuterIPRange") is not None else None,
                        "VxLANRange": VxLANRange.from_dict(obj["VxLANRange"]) if obj.get("VxLANRange") is not None else None,
                        "VxLANStackName": obj.get("VxLANStackName"),
                        "id": obj.get("id"),
                        "links": ( [APILink.from_dict(_item) for _item in obj.get("links", [])] if obj.get("links") is not None else None)
            ,
            "links": obj.get("links")
        })
        return _obj


